stages:
  parse_pdb:
    foreach: ${stages.parse_pdb}
    do:
      cmd: python ${item.script} ${item.params}
      deps:
        - ${item.script}
        - ${item.params.pdb_dir}
      outs:
        - ${item.params.output_fasta}
        - ${item.params.output_parquet}

  filter_sequences:
    foreach: ${stages.filter_sequences}
    do:
      cmd: python ${item.script} ${item.params}
      deps:
        - ${item.script}
        - ${item.params.input_parquet}
        - ${item.params.input_fasta}
      outs:
        - ${item.params.output_parquet}
        - ${item.params.output_fasta}

  mmseqs2:
    cmd: python ${stages.mmseqs2.script} ${stages.mmseqs2.params}
    deps:
      - ${stages.mmseqs2.script}
      - ${stages.mmseqs2.params.train_fasta}
      - ${stages.mmseqs2.params.test_fasta}
    outs:
      - ${stages.mmseqs2.params.combined_fasta}
      - ${stages.mmseqs2.params.cluster_output_tsv}
      - ${stages.mmseqs2.params.search_output_tsv}

  prepare_dataset:
    cmd: python ${stages.prepare_dataset.script} ${stages.prepare_dataset.params}
    deps:
      - ${stages.prepare_dataset.script}
      - ${stages.prepare_dataset.params.train_seq_path}
      - ${stages.prepare_dataset.params.test_seq_path}
      - ${stages.prepare_dataset.params.validation_pdbs_path}
    outs:
      - ${stages.prepare_dataset.params.output_train_path}
      - ${stages.prepare_dataset.params.output_val_path}
      - ${stages.prepare_dataset.params.output_test_path}
      - ${stages.prepare_dataset.params.output_stats_path}

  train:
    cmd: python ${stages.train.script} --model ${stages.train.params.model._target_} --datamodule ${stages.train.params.datamodule._target_} ${stages.train.params}
    deps: 
      - ${stages.train.params.datamodule.train_dataset_path}
      - ${stages.train.params.datamodule.val_dataset_path}
    outs:
      - ${stages.train.params.trainer.output_dir}

  predict:
    foreach: ${stages.predict}
    do:
      cmd: python ${item.script} --model ${item.params.model._target_} --datamodule ${item.params.datamodule._target_} ${item.params}
      deps:
        - ${item.params.datamodule.test_dataset_path}
      outs:
        - ${item.params.output_predictions_path}

  # evaluate:
  #   cmd: python ${stages.evaluate.script} ${stages.evaluate.params}
  #   deps:
  #     - ${stages.evaluate.script}
  #     - ${stages.evaluate.params.checkpoint_path}
  #     - ${stages.evaluate.params.test_dataset_path}
  #   outs:
  #     - ${stages.evaluate.params.results_dir}/