model:
  _target_: esm2_unsupervised_baseline
  name: esm2_unsupervised_baseline
  backbone: facebook/esm2_t33_650M_UR50D
  learning_rate: 0.005
  weight_decay: 0.001
datamodule:
  _target_: protein_datamodule
  name: all seqs
  batch_size: 1
  num_workers: 4
  max_seq_length: 1024
  tokenizer_name: facebook/esm2_t33_650M_UR50D
  include_b_factors: false
  contact_threshold: 8.0
  train_dataset_path: output/datasets/train.pt
  val_dataset_path: output/datasets/val.pt
  test_dataset_path: output/datasets/test.pt
  sampler:
    cluster_path: output/mmseqs/all_seqs_clust.tsv
    train_n_pdb: 1.0
    train_intersect_val_clusters: true
    train_intersect_test_clusters: true
    val_n_pdb: 1.0
    test_n_pdb: 1.0
    train_max_chains_per_pdb: 1
    val_max_chains_per_pdb: 1
trainer:
  output_dir: output/train_checkpoints
  max_epochs: 300
  log_every_n_steps: 10
  accumulate_grad_batches: 4
  checkpoint:
    monitor: val_precision_long@L/5
    mode: max
    save_top_k: 1
    save_last: false
  early_stopping:
    monitor: val_precision_long@L/5
    patience: 10
    mode: max
stages:
  parse_pdb:
    train:
      script: src/parse_pdb.py
      params:
        pdb_dir: ../data/train
        split: train
        output_fasta: output/train_data/train.fasta
        output_parquet: output/train_data/train.parquet
    test:
      script: src/parse_pdb.py
      params:
        pdb_dir: ../data/test
        split: test
        output_fasta: output/test_data/test.fasta
        output_parquet: output/test_data/test.parquet
  mmseqs2:
    script: src/run_mmseqs2.py
    params:
      train_fasta: output/train_data/train_filtered.fasta
      test_fasta: output/test_data/test_filtered.fasta
      combined_fasta: output/mmseqs/all_seq.fasta
      db_path: output/mmseqs/all_seqs_db
      cluster_coverage: 0.8
      cluster_min_seq_id: 0.3
      cluster_tmp_dir: /tmp
      cluster_output_tsv: output/mmseqs/all_seqs_clust.tsv
      search_coverage: 0.8
      search_min_seq_id: 0.3
      search_tmp_dir: /tmp
      search_output_tsv: output/mmseqs/all_seqs_similarity.tsv
  filter_sequences:
    train:
      script: src/filter_sequences.py
      params:
        input_parquet: output/train_data/train.parquet
        input_fasta: output/train_data/train.fasta
        output_parquet: output/train_data/train_filtered.parquet
        output_fasta: output/train_data/train_filtered.fasta
        min_length: 30
        max_length: 1000
        max_x_fraction: 0.1
        max_b_factor: 100.0
    test:
      script: src/filter_sequences.py
      params:
        input_parquet: output/test_data/test.parquet
        input_fasta: output/test_data/test.fasta
        output_parquet: output/test_data/test_filtered.parquet
        output_fasta: output/test_data/test_filtered.fasta
        min_length: 30
        max_length: 1000
        max_x_fraction: 0.1
        max_b_factor: 100.0
  prepare_dataset:
    script: src/prepare_dataset.py
    params:
      train_seq_path: output/train_data/train_filtered.parquet
      test_seq_path: output/test_data/test_filtered.parquet
      validation_pdbs_path: ../data/selected_validation_pdbs.json
      output_train_path: output/datasets/train.pt
      output_val_path: output/datasets/val.pt
      output_test_path: output/datasets/test.pt
      output_stats_path: output/datasets/stats.json
      max_seq_length: 1024
  train:
    script: src/train.py
    params:
      trainer:
        output_dir: output/train_checkpoints
        max_epochs: 300
        log_every_n_steps: 10
        accumulate_grad_batches: 4
        checkpoint:
          monitor: val_precision_long@L/5
          mode: max
          save_top_k: 1
          save_last: false
        early_stopping:
          monitor: val_precision_long@L/5
          patience: 10
          mode: max
      model:
        _target_: esm2_unsupervised_baseline
        name: esm2_unsupervised_baseline
        backbone: facebook/esm2_t33_650M_UR50D
        learning_rate: 0.005
        weight_decay: 0.001
      datamodule:
        _target_: protein_datamodule
        name: all seqs
        batch_size: 1
        num_workers: 4
        max_seq_length: 1024
        tokenizer_name: facebook/esm2_t33_650M_UR50D
        include_b_factors: false
        contact_threshold: 8.0
        train_dataset_path: output/datasets/train.pt
        val_dataset_path: output/datasets/val.pt
        test_dataset_path: output/datasets/test.pt
        sampler:
          cluster_path: output/mmseqs/all_seqs_clust.tsv
          train_n_pdb: 1.0
          train_intersect_val_clusters: true
          train_intersect_test_clusters: true
          val_n_pdb: 1.0
          test_n_pdb: 1.0
          train_max_chains_per_pdb: 1
          val_max_chains_per_pdb: 1
  predict:
    val:
      script: src/predict.py
      params:
        trainer:
          output_dir: output/train_checkpoints
          max_epochs: 300
          log_every_n_steps: 10
          accumulate_grad_batches: 4
          checkpoint:
            monitor: val_precision_long@L/5
            mode: max
            save_top_k: 1
            save_last: false
          early_stopping:
            monitor: val_precision_long@L/5
            patience: 10
            mode: max
        model:
          _target_: esm2_unsupervised_baseline
          name: esm2_unsupervised_baseline
          backbone: facebook/esm2_t33_650M_UR50D
          learning_rate: 0.005
          weight_decay: 0.001
        datamodule:
          _target_: protein_datamodule
          name: all seqs
          batch_size: 1
          num_workers: 4
          max_seq_length: 1024
          tokenizer_name: facebook/esm2_t33_650M_UR50D
          include_b_factors: false
          contact_threshold: 8.0
          train_dataset_path: output/datasets/train.pt
          val_dataset_path: output/datasets/val.pt
          test_dataset_path: output/datasets/val.pt
          sampler:
            cluster_path: output/mmseqs/all_seqs_clust.tsv
            train_n_pdb: 1.0
            train_intersect_val_clusters: true
            train_intersect_test_clusters: true
            val_n_pdb: 1.0
            test_n_pdb: 1.0
            train_max_chains_per_pdb: 1
            val_max_chains_per_pdb: 1
        checkpoint_name: best
        output_predictions_path: output/predictions/val.pkl
    test:
      script: src/predict.py
      params:
        trainer:
          output_dir: output/train_checkpoints
          max_epochs: 300
          log_every_n_steps: 10
          accumulate_grad_batches: 4
          checkpoint:
            monitor: val_precision_long@L/5
            mode: max
            save_top_k: 1
            save_last: false
          early_stopping:
            monitor: val_precision_long@L/5
            patience: 10
            mode: max
        model:
          _target_: esm2_unsupervised_baseline
          name: esm2_unsupervised_baseline
          backbone: facebook/esm2_t33_650M_UR50D
          learning_rate: 0.005
          weight_decay: 0.001
        datamodule:
          _target_: protein_datamodule
          name: all seqs
          batch_size: 1
          num_workers: 4
          max_seq_length: 1024
          tokenizer_name: facebook/esm2_t33_650M_UR50D
          include_b_factors: false
          contact_threshold: 8.0
          train_dataset_path: output/datasets/train.pt
          val_dataset_path: output/datasets/val.pt
          test_dataset_path: output/datasets/test.pt
          sampler:
            cluster_path: output/mmseqs/all_seqs_clust.tsv
            train_n_pdb: 1.0
            train_intersect_val_clusters: true
            train_intersect_test_clusters: true
            val_n_pdb: 1.0
            test_n_pdb: 1.0
            train_max_chains_per_pdb: 1
            val_max_chains_per_pdb: 1
        checkpoint_name: best
        output_predictions_path: output/predictions/test.pkl
data_dir: ../data
output_dir: output
