model:
  _target_: models.esm2_contact_predictor.ESM2ContactPredictor
  model_name: facebook/esm2_t30_150M_UR50D
  num_layers: 30
  embed_dim: 640
  attention_heads: 20
  dropout: 0.1
  contact_prediction_head: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-05
  weight_decay: 0.01
scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.001
  total_steps: 10000
dataloader:
  batch_size: 32
  num_workers: 4
  max_seq_length: 1024
  tokenizer_name: models.esm2_contact_predictor.ESM2ContactPredictor
  include_b_factors: false
  contact_threshold: 8.0
stages:
  parse_pdb:
    train:
      script: src/parse_pdb.py
      params:
        pdb_dir: ../data/train
        split: train
        output_fasta: output/train_data/train.fasta
        output_parquet: output/train_data/train.parquet
    test:
      script: src/parse_pdb.py
      params:
        pdb_dir: ../data/test
        split: test
        output_fasta: output/test_data/test.fasta
        output_parquet: output/test_data/test.parquet
  mmseqs2:
    script: src/run_mmseqs2.py
    params:
      train_fasta: output/train_data/train_filtered.fasta
      test_fasta: output/test_data/test_filtered.fasta
      combined_fasta: output/mmseqs/all_seq.fasta
      db_path: output/mmseqs/all_seqs_db
      cluster_coverage: 0.8
      cluster_min_seq_id: 0.3
      cluster_tmp_dir: /tmp
      cluster_output_tsv: output/mmseqs/all_seqs_clust.tsv
      search_coverage: 0.8
      search_min_seq_id: 0.3
      search_tmp_dir: /tmp
      search_output_tsv: output/mmseqs/all_seqs_similarity.tsv
  filter_sequences:
    train:
      script: src/filter_sequences.py
      params:
        input_parquet: output/train_data/train.parquet
        input_fasta: output/train_data/train.fasta
        output_parquet: output/train_data/train_filtered.parquet
        output_fasta: output/train_data/train_filtered.fasta
        min_length: 30
        max_length: 1000
        max_x_fraction: 0.1
        max_b_factor: 100.0
    test:
      script: src/filter_sequences.py
      params:
        input_parquet: output/test_data/test.parquet
        input_fasta: output/test_data/test.fasta
        output_parquet: output/test_data/test_filtered.parquet
        output_fasta: output/test_data/test_filtered.fasta
        min_length: 30
        max_length: 1000
        max_x_fraction: 0.1
        max_b_factor: 100.0
  prepare_dataset:
    script: src/prepare_dataset.py
    params:
      train_seq_path: output/train_data/train_filtered.parquet
      test_seq_path: output/test_data/test_filtered.parquet
      validation_pdbs_path: ../data/selected_validation_pdbs.json
      output_train_path: output/datasets/train.pt
      output_val_path: output/datasets/val.pt
      output_test_path: output/datasets/test.pt
      output_stats_path: output/datasets/stats.json
      max_seq_length: 1024
  train:
    script: src/train.py
    params:
      train_dataset_path: output/datasets/train.pt
      val_dataset_path: output/datasets/val.pt
      test_dataset_path: output/datasets/test.pt
      output_dir: output/checkpoints
      log_dir: output/logs
      max_epochs: 100
      val_check_interval: 0.5
      gradient_clip_val: 1.0
      accumulate_grad_batches: 1
      model:
        _target_: models.esm2_contact_predictor.ESM2ContactPredictor
        model_name: facebook/esm2_t30_150M_UR50D
        num_layers: 30
        embed_dim: 640
        attention_heads: 20
        dropout: 0.1
        contact_prediction_head: true
      dataloader:
        batch_size: 32
        num_workers: 4
        max_seq_length: 1024
        tokenizer_name: models.esm2_contact_predictor.ESM2ContactPredictor
        include_b_factors: false
        contact_threshold: 8.0
      early_stopping:
        patience: 10
        monitor: val_loss
        mode: min
      model_checkpoint:
        monitor: val_contact_precision
        mode: max
        save_top_k: 3
  evaluate:
    script: src/evaluate.py
    params:
      checkpoint_path: output/checkpoints/best_model.ckpt
      test_dataset_path: output/datasets/test.pt
      results_dir: output/evaluation
      predictions_path: output/evaluation/predictions.csv
      metrics_path: output/evaluation/metrics.json
      dataloader:
        batch_size: 32
        num_workers: 4
        max_seq_length: 1024
        tokenizer_name: models.esm2_contact_predictor.ESM2ContactPredictor
        include_b_factors: false
        contact_threshold: 8.0
      metrics:
      - precision
      - recall
      - f1_score
      - accuracy
      - contact_precision_at_k:
        - 1
        - 5
        - 10
      visualize:
        num_samples: 10
        save_contact_maps: true
data_dir: ../data
output_dir: output
