defaults:
  - _self_

script: src/train.py
params:
  trainer:
    output_dir: ${output_dir}/train_checkpoints
    max_epochs: 100
    log_every_n_steps: 10
    accumulate_grad_batches: 1
    checkpoint:
      monitor: val_contact_precision
      mode: max
      save_top_k: 3
      save_last: true
    early_stopping:
      monitor: val_loss
      patience: 10
      mode: min
  # Use global model and datamodule settings
  model: ${model}
  datamodule: ${datamodule}