# @package _global_
defaults:
  - _self_

datamodule:
  _target_: "base_datamodule"  # Reference to registered data module class
  name: "base" # Name of data module for better comparison
  batch_size: 32
  num_workers: 4
  max_seq_length: 1024
  tokenizer_name: ${model.backbone}
  include_b_factors: false
  contact_threshold: 8.0 