# @package _global_
defaults:
  - _self_


dataloader:
  batch_size: 32
  num_workers: 4
  max_seq_length: 1024
  tokenizer_name: ${model.model_name}
  include_b_factors: true
  contact_threshold: 8.0 