defaults:
  - base

name: "1 seq from pdb except cluster"
batch_size: 4
sampler:
  train_n_pdb: 1.0
  train_intersect_val_clusters: false
  train_intersect_test_clusters: false
  val_n_pdb: 1.0
  test_n_pdb: 1.0
  train_max_chains_per_pdb: 1 # they none by default
  val_max_chains_per_pdb: 1
  # test_max_chains_per_pdb: null