defaults:
  - _self_

_target_: "paired_protein_datamodule"  # Reference to registered data module class
name: "paired base" # Name of data module for better comparison
batch_size: 1
num_workers: 1
max_seq_length: 1024
tokenizer_name: ${model.backbone}
include_b_factors: false
contact_threshold: 8.0
train_dataset_path: ${output_dir}/datasets/train.pt
val_dataset_path: ${output_dir}/datasets/val.pt
test_dataset_path: ${output_dir}/datasets/test.pt
similarity_file_path: ${output_dir}/mmseqs/all_seqs_similarity.tsv
min_similarity_threshold: 0.3
max_similarity_threshold: 0.95
sampler:
  cluster_path: ${output_dir}/mmseqs/all_seqs_clust.tsv
  train_n_pdb: 1.0
  train_intersect_val_clusters: true
  train_intersect_test_clusters: true
  val_n_pdb: 1.0
  test_n_pdb: 1.0
  train_max_chains_per_pdb: 1 # they none by default
  val_max_chains_per_pdb: 1