defaults:
  - _self_

output_dir: ${output_dir}/train_checkpoints
max_epochs: 300
log_every_n_steps: 10
accumulate_grad_batches: 2
val_check_interval: 300
checkpoint:
  monitor: val_precision_long@L/5
  mode: max
  save_top_k: 1
  save_last: false
early_stopping:
  monitor: val_precision_long@L/5
  patience: 10
  mode: max