defaults:
  - _self_


_target_: "esm2_unsupervised_baseline"  # Reference to baseline model
name: "esm2_unsupervised_baseline"  # Backbone model name
backbone: facebook/esm2_t33_650M_UR50D
# Training settings
learning_rate: 1e-3
weight_decay: 1e-4 