# @package _global_
defaults:
  - esm2_small

model:
  model_name: "facebook/esm2_t30_150M_UR50D"
  num_layers: 30
  embed_dim: 640
  attention_heads: 20

optimizer:
  lr: 5e-5  # Lower learning rate for larger model 