# @package _global_
defaults:
  - _self_

model:
  _target_: "esm2_contact_predictor"  # Reference to registered model class
  backbone: "esm2_small"  # Backbone model name
  name: "esm2_small" # Name of model for better comparison
  dropout: 0.1
  contact_prediction_head: true
  freeze_backbone: true
  
  # Training settings (will use model-specific defaults based on 'name')
  optimizer_lr: 1e-4
  optimizer_weight_decay: 0.01
  scheduler_max_lr: 1e-3
  scheduler_total_steps: 10000 