defaults: 
  - esm2_lora_contact_650m

_target_: esm2_lora_contactconv
name: "esm2 lora with conv refiner"
cnn_kernel_size: 5

learning_rate: 5e-4  # Lower learning rate for larger model
weight_decay: 1e-4 