# @package _global_
defaults:
  - _self_

model:
  _target_: "esm2_contact_predictor"  # Reference to registered model class
  name: "esm2_large"  # Backbone model name
  dropout: 0.1
  contact_prediction_head: true
  freeze_backbone: true  # Large model frozen by default
  
  # Training settings (will use model-specific defaults based on 'name')
  optimizer_lr: 2e-5
  optimizer_weight_decay: 0.01
  scheduler_max_lr: 2e-4
  scheduler_total_steps: 20000
